# Generated by Django 4.2.7 on 2023-11-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="activity",
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("path", models.TextField(blank=True)),
                ("command", models.TextField(null=True)),
                ("description", models.CharField(max_length=200, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bot.activity",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="program",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="bot.program"
            ),
        ),
    ]
