# Generated by Django 4.2.7 on 2023-11-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_remove_room_activity_program_room_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="title",
            field=models.TextField(default="Untitled program"),
        ),
    ]
