# Generated by Django 4.2.7 on 2024-07-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_program_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
