# Generated by Django 4.2.7 on 2024-07-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_program_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
