# Generated by Django 4.2.7 on 2024-07-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_program_is_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='activity',
        ),
        migrations.AlterField(
            model_name='program',
            name='command',
            field=models.TextField(default='None', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='path',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
