# Generated by Django 5.1 on 2025-03-26 19:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_program_activity_alter_program_command_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='hour',
            field=models.TimeField(default=datetime.time(19, 0, 20, 209994)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
