# Generated by Django 5.1 on 2025-05-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='args',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='handler',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='command',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
