# Generated by Django 5.1 on 2025-05-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_command_args_command_handler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
