# Generated by Django 5.1 on 2025-05-06 18:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_program_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_ip', models.GenericIPAddressField(help_text='The unique local IP address of the client.', protocol='IPv4', unique=True)),
                ('port', models.IntegerField(help_text='The port number the client application is listening on.', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)])),
                ('allowed_users', models.ManyToManyField(help_text='Users who are allowed to access this client.', related_name='allowed_clients', to=settings.AUTH_USER_MODEL)),
                ('main_user', models.ForeignKey(blank=True, help_text='The primary user associated with this client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
