# Generated by Django 5.1 on 2025-05-07 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['local_ip', 'main_user']},
        ),
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['client__local_ip', 'client__port', 'command_id'], 'verbose_name': 'Command', 'verbose_name_plural': 'Commands'},
        ),
        migrations.AddField(
            model_name='command',
            name='client',
            field=models.ForeignKey(help_text='The client this command belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='bot.client'),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='command',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='command',
            constraint=models.UniqueConstraint(fields=('client', 'command_id'), name='unique_command_per_client'),
        ),
    ]
