# Generated by Django 5.1 on 2025-05-08 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bot', '0013_alter_client_options_alter_command_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(help_text='The user associated with these settings.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('client_api_keys', models.JSONField(blank=True, default=dict, help_text='A dictionary mapping client IPs to their API keys for this user.', null=True)),
            ],
        ),
    ]
