# Generated by Django 5.1 on 2025-05-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the client machine (e.g., computer name).', max_length=255, null=True),
        ),
    ]
