# Generated by Django 5.1 on 2025-05-13 15:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_client_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='room',
            name='program',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['client__local_ip', 'client__port', 'name'], 'verbose_name': 'Command', 'verbose_name_plural': 'Commands'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-available', 'name'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'ordering': ['user'], 'verbose_name': 'User Settings', 'verbose_name_plural': 'Users Settings'},
        ),
        migrations.RemoveConstraint(
            model_name='command',
            name='unique_command_per_client',
        ),
        migrations.RemoveField(
            model_name='command',
            name='command_id',
        ),
        migrations.RemoveField(
            model_name='command',
            name='handler',
        ),
        migrations.RemoveField(
            model_name='program',
            name='command',
        ),
        migrations.RemoveField(
            model_name='program',
            name='path',
        ),
        migrations.AddField(
            model_name='command',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 13, 15, 1, 47, 958620, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 13, 15, 1, 51, 263574, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.activity'),
        ),
        migrations.AddField(
            model_name='program',
            name='client',
            field=models.ForeignKey(help_text='The client this program is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='bot.client'),
        ),
        migrations.AddField(
            model_name='program',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 13, 15, 1, 54, 571692, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='The timestamp when the program finished.', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='The timestamp when the program was started.', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 13, 15, 1, 59, 361925, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersettings',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 13, 15, 2, 3, 218853, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='available',
            field=models.BooleanField(default=False, help_text='Indicates if the program is currently available for execution.'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(default='None', help_text='A brief description of the program.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_running',
            field=models.BooleanField(default=False, help_text='Indicates if the program is currently running.'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.TextField(help_text='The internal name or identifier for the program. No spaces or special characters. Only [a-zA-Z0-9_].'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.TextField(default='Untitled program', help_text='The display title for the program.'),
        ),
        migrations.AddConstraint(
            model_name='command',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='unique_command_per_client'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
