# Generated by Django 5.1 on 2025-05-16 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_command_created_alter_command_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='hour',
        ),
        migrations.AddField(
            model_name='activity',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
