# Generated by Django 5.1 on 2025-05-16 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_remove_activity_date_remove_activity_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
