# Generated by Django 5.1 on 2025-05-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_alter_activity_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user_config',
            field=models.JSONField(blank=True, default=dict, help_text='A dictionary for storing user-specific configuration settings.', null=True),
        ),
    ]
