# Generated by Django 5.1 on 2025-05-21 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_alter_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
