# Generated by Django 5.1 on 2025-05-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_alter_message_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='likes',
        ),
    ]
