# Generated by Django 5.1 on 2025-05-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_remove_message_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.JSONField(blank=True, default=list, help_text='A list of user IDs who liked this message.', null=True),
        ),
    ]
