# Generated by Django 5.1 on 2025-06-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_message_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='title',
            field=models.TextField(default='Untitled command'),
        ),
    ]
